### ISSUE TITLE
11.03.24 crash on first load of mod with new save

### ISSUE THREAD

**Issue by Zuzakiin** [LarsEKrueger/hunter-killer#1]
Save has many hours over the last week with some modded spidertrons.
Current manually directed combat spiders are named Hunter. None named Killer yet.
No map marker called Homebase yet.
Crash happens within 30 seconds or so after load.
Tried to race it by quick making map marker named Homebase, game crashed before could confirm text box.
Tried renaming a spider too, crash before confirmed.

 79.825 Script @__skins-factored__/control.lua:262: Runtime initalizing
  99.712 Error MainLoop.cpp:1429: Exception at tick 11700000: The mod Hunter and Killer Spidertrons (0.6.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event hunter-killer::on_nth_tick(3600)
__hunter-killer__/control.lua:1194: bad argument #2 of 2 to 'table_size' (table expected, got nil)
stack traceback:
	[C]: in function 'table_size'
	__hunter-killer__/control.lua:1194: in function <__hunter-killer__/control.lua:1192>

simple fix, or at least I thought so based on my personal mods that don't do table stuff
I tried a bunch of error catches that usually work for non tables including changing the 0 to nil, nope.

**Comment by Zuzakiin** [comment]
Found a solution. simple in hindsight. forget the table stuff, check for only the variable. change
   if table_size(storage.homebases) ==  0
   if storage.homebases == nil or 0 then

**Comment by Zuzakiin** [comment]
no crash, but for some reason the message pops up again after creating map tag, renaming/copying killer name to multiple spiders and a bunch more indicating deployment.
look at em go!
hmm. a small squad of two against a small biter base left the worms behind despite plenty of ammo and minimal shield damage. then they go on other side of base. \o/
Then again, I've done that myself a few times with long waypoint chains.
...
and now they  stopped. with no Homebase message blinking again despite it being on the map near ammo and stuff as: Homebase, and all spiders still have plenty of ammo and full hitpoints.
So, for whatever reason it is not detecting plaintext map tag of exactly and only: Homebase
It is in fact the only map tag I have cuz I usually use train stations as such.

**Comment by LarsEKrueger** [comment]
I'll have a look. Not having a Homebase Marker should not be a problem, but I never tried it with a new save.--Gesendet mit der GMX Mail AppAm 04.11.24, 01:37 schrieb Zuzakiin ***@***.***>:

Save has many hours over the last week with some modded spidertrons.
Current manually directed combat spiders are named Hunter. None named Killer yet.
No map marker called Homebase yet.
Crash happens within 30 seconds or so after load.
Tried to race it by quick making map marker named Homebase, game crashed before could confirm text box.
Tried renaming a spider too, crash before confirmed.
79.825 Script @skins-factored/control.lua:262: Runtime initalizing
99.712 Error MainLoop.cpp:1429: Exception at tick 11700000: The mod Hunter and Killer Spidertrons (0.6.0) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event hunter-killer::on_nth_tick(3600)
hunter-killer/control.lua:1194: bad argument #2 of 2 to 'table_size' (table expected, got nil)
stack traceback:
[C]: in function 'table_size'
hunter-killer/control.lua:1194: in function <hunter-killer/control.lua:1192>
simple fix, or at least I thought so based on my personal mods that don't do table stuff
I tried a bunch of error catches that usually work for non tables including changing the 0 to nil, nope.

**Comment by LarsEKrueger** [comment]
This sounds like a message from a different mod. If you could look in control.lua for game.print for the message (should be about 5 places) and pinpoint which message is issued, I can try to suppress it Am 04.11.24, 01:52 schrieb Zuzakiin ***@***.***>:

no crash, but for some reason the message pops up again after creating map tag, renaming/copying killer name to multiple spiders and a bunch more indicating deployment.
look at em go!

**Comment by LarsEKrueger** [comment]
Fixed in 0.6.1
